### ISSUE TITLE
source on website is incorrect (for people not logged into the the organization)

### ISSUE THREAD

**Issue by elil** [clawpack/clawpack.github.com#7]
The source link on the website links to http://github.com/organizations/clawpack which probably works if you are a member of the clawpack organization and logged in, otherwise, it doesn't work.  http://github.com/clawpack probably works in all cases.

There are numerous references to this url, although some may be intended that way.  https://github.com/clawpack/clawpack.github.com/search?utf8=%E2%9C%93&q=%22https%3A%2F%2Fgithub.com%2Forganizations%2Fclawpack%2F%22&type=Code

**Comment by ketch** [comment]
This seems to be caused by a change github has made.  I think we should replace those links with

http://github.com/orgs/clawpack

which redirects to github.com/clawpack if you are not a member of the organization.  Also,

https://github.com/orgs/clawpack/dashboard

works fine whether you are a member or not.

**Comment by rjleveque** [comment]
Sounds fine to me.  Thanks for the heads up.
